### ISSUE TITLE
Write to two buckets for different purposes

### ISSUE THREAD

**Issue by not-the-fish** [dssg/metta-data#13]
We'll be saving train/test splits to disk for two purposes:

1. Cross-project research
2. Within project development/testing/research

Matrices for these should go to different destinations.

For the first, Metta should save only (what is believed at the time to be) _pristine_ matrices, and it should _overwrite_ matrices when it runs, in case something in feature generation is updated.

For the second matrices should go to a project bucket, where matrices should *not* be overwritten but should be saved regardless.

One solution to the overwriting vs. creating new file problem might be to require a `batch_id` in the metadata that is excluded from the hash in the first case but included in the hash in the second, producing a new uuid for the same configuration in each batch.

To manage destinations, the key for bucket_name might be passed (e.g., `bucket_key = 'project_bucket_name'` or `bucket_key = 'research_bucket_name'`), and the behavior depend on the key name passed or an additional parameter passed.

**Comment by not-the-fish** [comment]
add timestamp to uuid in filenames to distinguish matrices with the same uuid but from different modeling runs that may have different values if data cleaning or feature generation have changed.

**Comment by avishekrk** [comment]
For issues where the features values have changed but they are the same features I would suggest an overwrite switch when storing matrices. You can then pass a parameter to turn it on or off. You can also do this by adding a model_id or timestamp or some sort of attribute in the metadata about how the feature values were calculated. I'll add an overwrite switch. 

For bucket names. There is a single function to upload the contents of a directory to S3. I would just call the function for every different bucket you would want to upload to and pass the credentials of the bucket to the upload_to_s3 function.

**Comment by jtwalsh0** [comment]
The "within project bucket" should be a folder within the project's existing bucket. It would probably be best if we used a standard name for that folder so it's consistent across projects
