### ISSUE TITLE
Require a feature_frequency key

### ISSUE THREAD

**Issue by not-the-fish** [dssg/metta-data#14]
The metadata for a matrix should include a `feature_frequency` flag in the form:

    feature_frequency:
        value: 1
        unit: 'D'

where units are either `'D'` or `'M'`.

**Comment by not-the-fish** [comment]
feature_frequency can be a string in timedelta format ('1 month') instead of separate keys for unit and value.

**Comment by avishekrk** [comment]
I believe you can add this to the config without making any changes to metta.
