### ISSUE TITLE
Add an option to pass a filename instead of a DataFrame to archive_matrix

### ISSUE THREAD

**Issue by avishekrk** [dssg/metta-data#20]

**Comment by avishekrk** [comment]
https://github.com/dssg/metta-data/pull/22

**Comment by not-the-fish** [comment]
Thanks! This is working for me. :) Eventually, it would be ideal to check column names without pulling data into memory (pd.read statements) when paths are passed rather than dfs. Then mv/cp/rename the file rather than saving a new file.
